//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hammer
{
    using System;
    using System.Collections.Generic;
    
    public partial class dobavljaci_materijali
    {
        public int dobavljaci_id { get; set; }
        public int materijali_id { get; set; }
        public System.DateTime datum { get; set; }
        public Nullable<int> kolicina { get; set; }
    
        public virtual dobavljaci dobavljaci { get; set; }
        public virtual materijali materijali { get; set; }
    }
}
