//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hammer
{
    using System;
    using System.Collections.Generic;
    
    public partial class kooperanti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kooperanti()
        {
<<<<<<< HEAD
            this.gradilista = new HashSet<gradilista>();
=======
            this.izvode_radove = new HashSet<izvode_radove>();
>>>>>>> origin/master
        }
    
        public string oib { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string kontakt { get; set; }
        public string email { get; set; }
        public string opis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
<<<<<<< HEAD
        public virtual ICollection<gradilista> gradilista { get; set; }
=======
        public virtual ICollection<izvode_radove> izvode_radove { get; set; }
>>>>>>> origin/master
    }
}
