//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hammer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alati> alati { get; set; }
        public virtual DbSet<dobavljaci> dobavljaci { get; set; }
        public virtual DbSet<dobavljaci_materijali> dobavljaci_materijali { get; set; }
        public virtual DbSet<gradilista> gradilista { get; set; }
        public virtual DbSet<izracun> izracun { get; set; }
        public virtual DbSet<kooperanti> kooperanti { get; set; }
        public virtual DbSet<korisnik> korisnik { get; set; }
        public virtual DbSet<materijali> materijali { get; set; }
        public virtual DbSet<obracun_placa> obracun_placa { get; set; }
        public virtual DbSet<skladista> skladista { get; set; }
        public virtual DbSet<skladiste_materijali> skladiste_materijali { get; set; }
        public virtual DbSet<strojevi> strojevi { get; set; }
        public virtual DbSet<vozni_park> vozni_park { get; set; }
        public virtual DbSet<zaposlenici> zaposlenici { get; set; }
    }
}
