//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hammer
{
    using System;
    using System.Collections.Generic;
    
    public partial class zaposlenici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zaposlenici()
        {
            this.izracun = new HashSet<izracun>();
        }
    
        public string oib { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string strucna_sprema { get; set; }
        public string satnica { get; set; }
        public int gradilista_id { get; set; }
        public Nullable<System.DateTime> od { get; set; }
        public System.DateTime @do { get; set; }
        public Nullable<int> vozilo_id { get; set; }
    
        public virtual gradilista gradilista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izracun> izracun { get; set; }
        public virtual vozni_park vozni_park { get; set; }
    }
}
